package CCG;

public enum Type {
    FORWARD, BACKWARD, FORWARD_COMPOSITION, FORWARD_CROSSED_COMPOSITION, BACKWARD_COMPOSITION, BACKWARD_CROSSED_COMPOSITION, TYPE_RAISING_FORWARD, EXTRA_POSITION_BACKWARD, EXTRA_POSITION_BACKWARD_COMPOSITION, EXTRA_POSITION_BACKWARD_CROSSED_COMPOSITION
}
